on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - run: dotnet restore
      - run: dotnet build